version: '3.8'
services:

  linkstack:
    hostname: 'linkstack'
    image: 'linkstackorg/linkstack:latest'   
    environment:
      TZ: 'Europe/Berlin'
      SERVER_ADMIN: 'syttva@docastudios.com'
      HTTP_SERVER_NAME: 'links.docastudios.com'
      HTTPS_SERVER_NAME: 'links.docastudios.com'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    ports:
      - '8190:80'
    restart: unless-stopped
